dist: xenial
language: python

python:
  - "3.8"
  - "3.9"
  - "3.10"
  - "3.11"

install:
  - pip install -r requirements.txt
  - pip install pytest pytest-cov codecov flake8

script:
  - pytest --cov=webssh
  - flake8

after_success:
  - codecov
